StocksApp.Web/Controllers/StocksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.Extensions.Options;
using ServiceContracts;
using StocksApp.Web.Models;
using System.Security.Cryptography.Xml;

namespace StocksApp.Web.Controllers
{
    [Route("[controller]")]
    public class StocksController : Controller
    {
        private readonly IFinnhubService _finnhubService;
        private readonly TradingOptions _tradingOptions;
        private readonly ILogger<StocksController> _logger;
        public StocksController(IFinnhubService finnhubService, IOptions<TradingOptions> tradingOptions, ILogger<StocksController> logger)
        {
            _logger = logger;
            _finnhubService = finnhubService;
            _tradingOptions = tradingOptions.Value;
        }

        [Route("[action]/{stock?}")]
        [Route("~/[action]/{stock?}")]
        public async Task<IActionResult> Explore(string? stock, bool showAll = false)
        {
            //get company profile from API server
            List<Dictionary<string, string>>? stocksDictionary = await _finnhubService.GetStocks();

            List<Stock> stocks = new List<Stock>();

            if (stocksDictionary is not null)
            {
                //filter stocks
                if (!showAll && _tradingOptions.Top25PopularStocks != null)
                {
                    string[]? Top25PopularStocksList = _tradingOptions.Top25PopularStocks.Split(",");
                    if (Top25PopularStocksList is not null)
                    {
                        stocksDictionary = stocksDictionary
                         .Where(temp => Top25PopularStocksList.Contains(Convert.ToString(temp["symbol"])))
                         .ToList();
                    }
                }

                stocks = stocksDictionary
                 .Select(temp => new Stock() { StockName = Convert.ToString(temp["description"]), StockSymbol = Convert.ToString(temp["symbol"]) })
                .ToList();
            }

            ViewBag.stock = stock;
            return View(stocks);
        }
    }
}

StocksApp.Web/Controllers/TradeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using ServiceContracts;
using ServiceContracts.DTO;
using StocksApp.ServiceContracts;
using StocksApp.ServiceContracts.DTOs;
using StocksApp.Web.Filters.ActionFilters;
using StocksApp.Web.Models;
using System.Globalization;

namespace StocksApp.Web.Controllers
{
    [Route("[controller]")]
    public class TradeController : Controller
    {
        private readonly TradingOptions _tradingOptions;
        private readonly IFinnhubService _finnhubService;
        private readonly IStocksService _stockService; 
        private readonly IConfiguration _configuration;
        public TradeController(IOptions<TradingOptions> tradingOptions, IFinnhubService finnhubService, IStocksService stockService,IConfiguration configuration)
        {
            _tradingOptions = tradingOptions.Value;
            _finnhubService = finnhubService;
            _stockService = stockService;
            _configuration = configuration;
        }

        [Route("/")]
        [Route("[action]")]
        [Route("[action]/{symbol?}")]
        public async Task<IActionResult> Index(string? symbol)
        {
            if (string.IsNullOrEmpty(symbol))
                symbol = _tradingOptions.DefaultStockSymbol;

            var companyProfileDictionary = await _finnhubService.GetCompanyProfile(symbol);
            var stockPriceQuoteDictionary = await _finnhubService.GetStockPriceQuote(symbol);

            var stockTrade = new StockTrade() { StockSymbol = symbol };

            if (companyProfileDictionary != null && stockPriceQuoteDictionary != null)
            {
                stockTrade = new StockTrade()
                {
                    StockSymbol = Convert.ToString(companyProfileDictionary["ticker"]),
                    StockName = Convert.ToString(companyProfileDictionary["name"]),
                    Price = double.Parse(stockPriceQuoteDictionary["c"].ToString(), CultureInfo.InvariantCulture)
                };
            }

            ViewBag.FinnhubToken = _configuration["FinnhubToken"];

            return View(stockTrade);
        }


        [HttpPost]
        [Route("[action]")]
        [CreateOrderActionFactorory]
        public IActionResult SellOrder(SellOrderRequest request)
        {
            var response = _stockService.CreateSellOrder(request);
            return RedirectToAction(nameof(Orders));
        }

        [HttpPost]
        [Route("[action]")]
        [CreateOrderActionFactorory]
        public IActionResult BuyOrder(BuyOrderRequest request)
        {
            var response = _stockService.CreateBuyOrder(request);
            return RedirectToAction(nameof(Orders));
        }


        [Route("[action]")]
        public async Task<IActionResult> Orders()
        {
            List<BuyOrderResponse> buyOrders = await _stockService.GetBuyOrders();
            List<SellOrderResponse> sellOrders = await _stockService.GetSellOrders();

            var orders = new Orders()
            {
                BuyOrders = buyOrders,
                SellOrders = sellOrders
            };

            ViewBag.TradingOptions = _tradingOptions;

            return View(orders);
        }

        [Route("[action]")]
        public async Task<IActionResult> OrdersPDF()
        {
            var orders = new List<IOrderResponse>();
            var buyOrders = await _stockService.GetBuyOrders();
            var sellOrders = await _stockService.GetSellOrders();

            orders.AddRange(buyOrders);
            orders = orders.OrderByDescending(o => o.DateAndTimeOfOrder).ToList();

            ViewBag.TradingOptions = _tradingOptions;

            return new ViewAsPdf("OrdersPDF", orders, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Bottom = 20, Left = 20, Right = 20 }
            };


        }
    }
}

StocksApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title | Stocks</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <div class="container">
        <div class="page-content">
            <div class="margin-bottom">
                <div class="flex" id="top-bar-div">
                    <div class="flex-1" id="app-title-div">
                        <h1 class="app-title">
                            <i class="fa-solid fa-money-bill-trend-up"></i>
                            Stocks
                        </h1>
                    </div>

                    <div class="flex-1 pr" id="search-box-div">

                        <form type="post" asp-controller="Stocks" asp-action="Explore">
                            <input type="search" class="search-text" placeholder="Search Stocks" name="stock" />
                            <input type="submit" value="search in explore" class="button button-blue-back"/>
                        </form>
                        <i class="fa-solid fa-gear"></i>

                        @if(!User.Identity.IsAuthenticated){
                            <a asp-controller="Account" asp-action="Register" class="link-hover">Register</a>
                            <a asp-controller="Account" asp-action="Login" class="link-hover">Login</a>
                        }else{
                            @User.Identity?.Name
                            <a asp-controller="Account" asp-action="SignOut" class="link-hover">Signout</a>
                        }
                    </div>
                </div>

            </div>


            <div class="navbar mb">
                <ul>
                    @if (ViewBag.CurrentUrl == "~/Explore")
                    {
                        <li><a asp-controller="Stocks" asp-action="Explore" class="nav-active">Explore</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Stocks" asp-action="Explore">Explore</a></li>
                    }

                    @if (ViewBag.CurrentUrl == "~/Trade/Index")
                    {
                        <li><a href="#" class="nav-active">Trade</a></li>
                    }
                    else
                    {
                        <li><a href="#">Trade</a></li>
                    }

                    @if (ViewBag.CurrentUrl == "~/Trade/Orders")
                    {
                        <li><a asp-controller="Trade" asp-action="Orders" class="nav-active">Orders</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Trade" asp-action="Orders">Orders</a></li>
                    }
                </ul>
            </div>

            @RenderBody()
        </div>

    </div>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>